name: Snyk IaC Scan

on:
  workflow_dispatch:

jobs:
  snyk-iac-scan:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Snyk CLI
        run: npm install -g snyk
      
      - name: Run Snyk IaC scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --severity-threshold=medium --report
      
      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report-${{ matrix.repo }}
          path: snyk-report.json
